--baseURL = "http://sszblog.xyz/"
languageCode = "zh-CN"
title = "Shi.bro的博客"
toc = true

[author]
  name = "Shi.bro"

[params]
  author = "Shi.bro"
  subtitle = "我的个人博客"
  keywords = "java,博客,分享"
  description = "专注于IT互联网，JAVA、设计模式、程序员的生存方式"


[menu]

  [[menu.main]]
    identifier = "archives"
    name = "目录"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4

# 自定义文章摘要，默认是70
summaryLength = 10